export const ARTICLE_PUBLISH = "ARTICLE_PUBLISH";
export const ARTICLE_PUBLISH_LOADER_SET = "ARTICLE_PUBLISH_LOADER_SET";

export const ARTICLES_GET = "ARTICLES_GET";
export const ARTICLES_SET = "ARTICLES_SET";

export const ARTICLES_MY_GET = "ARTICLES_MY_GET";
export const ARTICLES_MY_SET = "ARTICLES_MY_SET";

export const ARTICLE_GET = "ARTICLE_GET";
export const ARTICLE_SET = "ARTICLE_SET";

export const ARTICLES_TO_REVIEW_GET = "ARTICLES_TO_REVIEW_GET";
export const ARTICLES_TO_REVIEW_SEt = "ARTICLES_TO_REVIEW_SET";

export const ARTICLES_PENDING_GET = "ARTICLES_PENDING_GET";
export const ARTICLES_PENDING_SET = "ARTICLES_PENDING_SET";
